version: '3.8'

services:
    pgsql:
        image: 'postgres:latest'
        ports:
            - "5431:5432"
        env_file:
            - env/pgsql.env
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - golang

networks:
    golang:
        driver: bridge
volumes:
    db_data:

